### ISSUE TITLE
'npm start' fails with errors

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#11]
After following the instructions in INSTALL.md, as of commit 8fd1e0ef I'm still getting failure with errors when I run `npm start`:

        $ pwd
        /home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal
        $ npm start
        
        > smoke-alarm-portal@0.0.0 start /home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal
        > node ./bin/www
        
        
        module.js:340
        throw err;
        ^
        Error: Cannot find module 'destroy'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/express/node_modules/send/index.js:14:15)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        
        npm ERR! smoke-alarm-portal@0.0.0 start: `node ./bin/www`
        npm ERR! Exit status 8
        npm ERR! 
        npm ERR! Failed at the smoke-alarm-portal@0.0.0 start script.
        npm ERR! This is most likely a problem with the smoke-alarm-portal package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node ./bin/www
        npm ERR! You can get their info via:
        npm ERR!     npm owner ls smoke-alarm-portal
        npm ERR! There is likely additional logging output above.
        npm ERR! System Linux 3.16.0-4-amd64
        npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
        npm ERR! cwd /home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal
        npm ERR! node -v v0.10.38
        npm ERR! npm -v 1.4.21
        npm ERR! code ELIFECYCLE
        npm WARN This failure might be due to the use of legacy binary "node"
        npm WARN For further explanations, please read
        /usr/share/doc/nodejs/README.Debian
        
        npm ERR! 
        npm ERR! Additional logging details can be found in:
        npm ERR!     /home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/npm-debug.log
        npm ERR! not ok code 0

After getting this error the first time, I did `sudo apt-get install nodejs-legacy`, in case it was due to the known Debian nodejs naming situation (see `/usr/share/doc/nodejs/README.Debian` on any Debian box where nodejs is installed), but that package didn't make any difference -- I get the same error on `npm start` afterwards.

@cecilia-donnelly are you able to start up the app, on your Debian laptop?

Relatedly: @cecilia-donnelly and @trystant are you able to deploy the app on demo.getasmokealarm.com?  (Also known as staging.getasmokealarm.com, but let's use the "demo" name -- details about that box are in asset-keys file and @cecilia-donnelly can get them, as can @jvasile who I think set up the box.)

It's still a bug if the instructions aren't working on my Debian box, but we need to know if the problem exists everywhere or just on some machines.

**Comment by kfogel** [comment]
Should add that I did look at the `npm-debug.log` file as recommended by the error output.  It contains this:

        0 info it worked if it ends with ok
        1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
        2 info using npm@1.4.21
        3 info using node@v0.10.38
        4 verbose run-script [ 'prestart', 'start', 'poststart' ]
        5 info prestart smoke-alarm-portal@0.0.0
        6 info start smoke-alarm-portal@0.0.0
        7 verbose unsafe-perm in lifecycle true
        8 info smoke-alarm-portal@0.0.0 Failed to exec start script
        9 error smoke-alarm-portal@0.0.0 start: `node ./bin/www`
        9 error Exit status 8
        10 error Failed at the smoke-alarm-portal@0.0.0 start script.
        10 error This is most likely a problem with the smoke-alarm-portal package,
        10 error not with npm itself.
        10 error Tell the author that this fails on your system:
        10 error     node ./bin/www
        10 error You can get their info via:
        10 error     npm owner ls smoke-alarm-portal
        10 error There is likely additional logging output above.
        11 error System Linux 3.16.0-4-amd64
        12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
        13 error cwd /home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal
        14 error node -v v0.10.38
        15 error npm -v 1.4.21
        16 error code ELIFECYCLE
        17 verbose exit [ 1, true ]

**Comment by trystant** [comment]
Hi Karl, I have a quick question; what's the last known good commit for you? I ask because it seems strange that a doc change would be the source of this issue. Have you been able to `git bisect` and determine when npm start last worked successfully?

**Comment by kfogel** [comment]
I've never successfully deployed the app (remember I had problems last
Friday morning too, and we had to deploy on Cecilia's laptop, which
fortunately worked). The doc change surely isn't the problem, I agree -- I
was just giving my HEAD commit so you'd know what version I was on.

You have no deployment issues on Debian yourself, right?

Best,
-K

**Comment by trystant** [comment]
My droplet is all right, and I am going to deploy the app to demo in order to be sure (that's where tomorrow's demo will be, correct?)

**Comment by cecilia-donnelly** [comment]
I've been able to deploy the app consistently, @kfogel. @trystant, let's
keep in touch as you deploy it on the demo server and make sure that's
working fine.



On Thu, Jun 18, 2015 at 9:17 AM, Mark Nyon <notifications@github.com> wrote:

> My droplet is all right, and I am going to deploy the app to demo in order
> to be sure (that's where tomorrow's demo will be, correct?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenTechStrategies/smoke-alarm-portal/issues/11#issuecomment-113170386>
> .
>



-- 
Cecilia Donnelly
Open Source Specialist
312-757-5411
cdonnelly@opentechstrategies.com

**Comment by kfogel** [comment]
Ok, good -- this is all a relief: if you two can deploy consistently, then
the problem is something funny with my box, and we can debug it when I'm
back. This means feature dev can continue to be the priority. How are we
doing on showing some visible sign of geographical/admin region parsing in
the app?

Best,
-K

**Comment by kfogel** [comment]
Assuming this was local pilot error of some kind, and closing.  I've got the application up and running now.
