### ISSUE TITLE
'npm install' gives warnings

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#12]
As of commit 8fd1e0ef, when I do the `npm install` step I get many warnings:

        $ npm install
        npm WARN unmet dependency /home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/karma/node_modules/http-proxy requires colors@'0.x.x' but will load
        npm WARN unmet dependency /home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/karma/node_modules/colors,
        npm WARN unmet dependency which is version 1.1.2
        npm WARN unmet dependency /home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/karma/node_modules/rimraf requires glob@'^4.4.2' but will load
        npm WARN unmet dependency /home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/karma/node_modules/glob,
        npm WARN unmet dependency which is version 5.0.10
        npm WARN unmet dependency /home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/supertest/node_modules/superagent requires methods@'1.0.1' but will load
        npm WARN unmet dependency /home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/supertest/node_modules/methods,
        npm WARN unmet dependency which is version 1.1.1
        nanoid@0.0.1 node_modules/nanoid
        ??? validator@3.40.1
        ??? async@1.2.1
        $ 

I don't know whether any of those are related to the later failure to launch the app described in issue #11, but in any case we should expect no warnings from any INSTALL.md step -- that way, when we _do_ get new warnings, we'll see them and pay attention to them.

**Comment by cecilia-donnelly** [comment]
@kfogel when I do `npm install` I get:

    nanoid@0.0.1 node_modules/nanoid
    ├── validator@3.40.1
    └── async@1.2.1


@trystant is installing it on the demo server now and will put any errors he sees into the relevant tickets.

**Comment by kfogel** [comment]
Assuming this was local pilot error of some kind, and closing.  I've got the application up and running now.
