### ISSUE TITLE
Finalize "permission to text" language.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#15]
The "Permission to send text messages" language on the front page is not ideal, as @jvasile pointed out:

> Some people like getting text messages, but I would never want to check that box, especially as it is written. It reads like the opt-in to let Red Cross spam me with SMS.
> 
> I'm not fully sure what the intent of that check box is, but maybe it could be improved by wording a prompt more like "What's the best way for us to follow up with you? We can text you, email you or just call you on the phone."

We should figure out what we want to do here.  It might be a radio-button selector: "What's the best way for us to schedule an appointment?  (text)  (voice call)  (email)"  ...with a link to the privacy policy as per issue #9.

**Comment by cecilia-donnelly** [comment]
@nttaylor points out that we should put this radio-button selector above the phone/email fields and show an asterisk (for required) next to the field that corresponds to their choice.  That is, if they say "text me" then we'll show that the phone number field is required.  If they choose "email" then the email address field will be required.

This solves the question of "how do we show that EITHER the phone number OR the email address is required, without adding a lot of words?"

**Comment by kfogel** [comment]
Note that what we really want is non-exclusive checkboxes:

[ ] Text me
[ ] Phone me
[ ] Email me


That way the Red Cross knows what its options are, and can select whichever one is best at the time.  Maybe that will be different for different regions!

(Hmmm, we should also save in the database what language the user localized the site into, so we know what language to contact them in.  I'll file a separate ticket about that.)

**Comment by kfogel** [comment]
Closing because no longer relevant.
