### ISSUE TITLE
Show response with region name

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/smoke-alarm-portal#16]
For demo-ing to an internal audience, we should show users that the app knows what region corresponds to the zipcode that was submitted.  The response messages will be something like:

Confirmation:
"Thank you for your request!  Someone from `<region>` will reach out to you for scheduling shortly"

Sorry:
"Sorry, this portal doesn't support scheduling for `<region>` yet."

We'll change these messages for production use, but this way the audience will understand a little better what's going on under the hood.

This should be a relatively small tweak to the issue #7 work that @trystant has been doing.

**Comment by trystant** [comment]
There is one sticky point; I originally uploaded all of these as separate records. For some reason, the document I have is uploading as one document, making the views invalid. Checking the JSON format between the original selected_counties & the version Karl submitted.

**Comment by trystant** [comment]
There is one sticky point; I originally uploaded all of these as separate records. For some reason, the document I have is uploading as one document, making the views invalid. Checking the JSON format between the original selected_counties & the version Karl submitted.

**Comment by trystant** [comment]
Disregard previous comment; user error

**Comment by kfogel** [comment]
Disregarding as instructed, but FWIW: yes, the format of selected_counties changed (in commit 4124d470).

**Comment by kfogel** [comment]
This issue has been long done.  Closing.
