### ISSUE TITLE
Field labels hard to see against image background.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#18]
Some of the field labels are hard to see against the image background, at least in my browser (see for example the "Email" label in the attached screenshot).  We will want the labels to be larger anyway, I suspect, for ADA compliance, but we should also adjust the image and the font color relative to each other so that there's no danger of suboptimal readability no matter where the browser arranges things.

![screenshot from 2015-06-20 11 06 36](https://cloud.githubusercontent.com/assets/401111/8265981/cdb65e06-1746-11e5-8118-15db9db5a71f.png)

**Comment by nttaylor** [comment]
I've put a semi-transparent background behind each label like the one behind the instruction text and now behind the text on the "thank you" page. What do we think?

**Comment by kfogel** [comment]
We think this issue is fully resolved :-).  Thank you, @nttaylor !
