### ISSUE TITLE
Blue "Submit" button a bit lost against the background image.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#19]
The Submit button doesn't stand out enough.  See attached screenshot.
![screenshot from 2015-06-20 12 21 52](https://cloud.githubusercontent.com/assets/401111/8265984/02477592-1747-11e5-9f2a-c35dd31384ab.png)

**Comment by nttaylor** [comment]
I've added a 3px white border around the button. This makes it stand out more but also makes it look different from DCSOps buttons. Which is more important? Personally I vote for visibility.

**Comment by kfogel** [comment]
Agree with you.  Closing this issue -- it looks good.
