### ISSUE TITLE
Use yes/no format for permission radio buttons.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#27]
For the "permission to send text messages" field, and any other boolean permission fields like it, we should offer two radio button choices: "yes" and "no" (field labels will get translated when we translate the site of course)

A single checkbox by itself doesn't communicate intent clearly enough to the user.  They need to see that they are answering "yes" or "no" to a question, and merely leaving an isolated checkbox unchecked doesn't make it clear enough that that is equivalent to responding "no".  (It's different when there's a long list of options and you're choosing one or N of them -- then the correspondence between options and selector elements is clear, and the meaning of checking a box or not is thus also clear.  But we don't have that situation here.)

As to what the default should be: I'd say default to "yes" for permission to text and "yes" for permission to email (since we're going to have a good privacy / non-harassment policy anyway), but we can check with the client and with others to see if there's any prior art on this question.

**Comment by cecilia-donnelly** [comment]
@kfogel:
Is this a duplicate of or alternative to #15?  That is, we had been thinking of showing the options email, text, and call (as in https://github.com/OpenTechStrategies/smoke-alarm-portal/issues/15#issuecomment-114812644).  Are we also thinking of yes/no options?

**Comment by kfogel** [comment]
Closing this.  I think I must have had these thoughts before the comment in #15.  The way described in #15 is the way to go, though.  Thanks for catching the contradiction!
