### ISSUE TITLE
5 digit zip code shows up as "10001-undefined" on sorry page

### ISSUE THREAD

**Issue by trystant** [OpenTechStrategies/smoke-alarm-portal#31]
When I downloaded this commit ef0ed246e663e1baccd65aea92719b91076ee276 and did a test on an address in NYC, the zip code showing up was "10026-undefined".

**Comment by kfogel** [comment]
Thanks, Mark.  I saw your fix come in in commit cb19e3404e2e (though there
were a lot of unrelated things in that commit too -- watch out for 'git
commit -a' maybe?).  Nice catch!  I see now the case I didn't test: a pure
5-digit number that is not a valid zip code :-).

I'm trying to start up my VPN here, to join you all in IRC for a bit before
going b to bed.

Best,
-K

**Comment by cecilia-donnelly** [comment]
@trystant @kfogel is this issue finished?  I think invalid zip codes now get a sensical error message, but I don't want to close this prematurely.

**Comment by trystant** [comment]
@cecilia-donnelly @kfogel  I believe that this can be closed, but let me confirm to be sure.

**Comment by kfogel** [comment]
Tested; no bug now, so closing.
