### ISSUE TITLE
Resize demo server.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#32]
The whole reason us_addresses.json had to be split into multiple files was because CouchDB couldn't inhale the whole thing at once on the demo server.  That's ridiculous -- we can all do it just fine on our laptops.  Problem is our demo server is underpowered.

Don't resize today, b/c there's a demo today (we think).  But do resize soon.

**Comment by cecilia-donnelly** [comment]
Increased to 1GB of RAM, which made #33 possible.
