### ISSUE TITLE
Convert zipcodes to strings

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/smoke-alarm-portal#34]
Once #33 is complete, we will store zipcodes as strings in the new schema.  This will obviate commits  77dc5f68 and b52cd2702.

**Comment by trystant** [comment]
In a nutshell, I'm using a Node ORM called [sequelize](https://github.com/sequelize/sequelize) to create the database, implement migrations for the schema and interact with the database. This will also result in the creation of models for the project.

**Comment by kfogel** [comment]
+1 to all of this, and thanks for taking the time to explain the plan!

**Comment by cecilia-donnelly** [comment]
@trystant, now that we've completed #33, is this also taken care of?

**Comment by trystant** [comment]
Yes, @cecilia-donnelly . This can be closed.
