### ISSUE TITLE
Place field labels inside text boxes

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/smoke-alarm-portal#36]
Instead of having field labels next to the text input fields, just place them inside (presumably grayed out).

**Comment by nttaylor** [comment]
What about the three checkboxes indicating how the user wishes to be contacted? There's no "inside" to write into. Would this one input have a "label" (like an explanatory line above the checkboxes in the same gray color that appears inside the text input fields)?

**Comment by cecilia-donnelly** [comment]
@nttaylor good point.  I think that's a reasonable idea.

**Comment by kfogel** [comment]
Talked to client.  I think we're going to go with a single field "Email and/or phone number" anyway (we don't really need two fields for the contact information).

**Comment by kfogel** [comment]
Hey @cwebber, I'd like to consult with you and @cecilia-donnelly tomorrow on a few things about this issue -- I think the information I need to finish it might be stuff that's relatively easy for you and Cecilia.

**Comment by kfogel** [comment]
Just so I have it in writing for myself:

* Placeholder text for "State" is missing
* Want City and State to be next to each other (changing City length to fit is okay)
* Need that second paragraph to go on the right (this is really issue #37)
* We can just make phone number required for now, "Email" still okay to collect, but optional.  (See also comment in issue #38.)

**Comment by kfogel** [comment]
Everything that matters in this issue has either been completed (in various commits) or moved to other issues.  Closing now.
