### ISSUE TITLE
Invalid zipcodes hang, don't show sorry page

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/smoke-alarm-portal#41]
The sorry page now works for zipcodes that are out of the region (see #40), but not for invalid zipcodes like "00000" or "5555."  The code is complaining about line 131 in routes/index.js, where we try to pass the county and state, which obviously don't exist for an invalid zipcode.

**Comment by kfogel** [comment]
Closing as per above commit, but see comment in code for improvements that still need to be made.
