### ISSUE TITLE
Phone and email validation errors are positioned wonkily.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#46]
As of commit 9c4e812a7f, our phone and email validation errors are showing up all wonky:

![screenshot from 2015-07-07 17-58-41](https://cloud.githubusercontent.com/assets/401111/8559417/4ae0e804-24d2-11e5-8802-053ba10ef9e5.png)

There's a comment added in views/index.jade about why this is so, and how some other planned changes might affect the way we fix it, but anyway this ticket is here to make sure we don't forget.

@cecilia-donnelly mentioned that some of @nttaylor's changes on the `15_contact_preference` branch might be useful for fixing the positioning of the error messages on the page.  I'm not sure, but I _think_ commit 3c4f07761ce on that branch is the relevant one, and that somewhere in the massive diff that is

    $ git diff 3c4f07761ce55b4f6e6ca3a4d5fdfb4c9dc29a09^..3c4f07761ce55b4f6e6ca3a4d5fdfb4c9dc29a09

is some material about better error message positioning.

**Comment by nttaylor** [comment]
Closing following 2138577
