### ISSUE TITLE
Set required fields

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/smoke-alarm-portal#5]
Required fields are name, zipcode, and (phone number or email address) (per @kfogel: https://github.com/OpenTechStrategies/smoke-alarm-portal/issues/4#issuecomment-112402646).  These should be marked by a red asterisk and return an error if the form is submitted without them.

Other fields (address, city, state) should not be required.

**Comment by trystant** [comment]
In terms of a merge commit, yes. I merged the updates that @nttaylor made earlier (nice, btw!)

**Comment by cecilia-donnelly** [comment]
This is done.  For the asterisks on email/phone, see my comment (forthcoming) in #15.
