### ISSUE TITLE
Reposition fields and text vertically

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/smoke-alarm-portal#54]
After looking at the changes made in #37, we're going to change the layout back to a more vertical look.  At the top of the page will be large text reading "Thank you..." as in the current left paragraph.  Then, smaller, we'll see the instructions beginning with "Please..." in that same paragraph.

Below that text will be the fields, closer together than they are as of 2809249c9474593db8bdd6c49422ed4131c5f530.  __All fields will be required.__

Below the fields and the submit button will be the "Currently available in..." text from the left paragraph and all the text from the right paragraph.  

At the very bottom we'll have the Red Cross logo.

See all this drawn below:
![20150710_145735](https://cloud.githubusercontent.com/assets/1497818/8627978/7baf05d0-2714-11e5-844a-60dbf8e3e5c8.jpg)

**Comment by cecilia-donnelly** [comment]
@kfogel, I assigned you for now because you've been doing the layout changes but @nttaylor and I can also do this.

**Comment by nttaylor** [comment]
Closing this issue because in spite of other issues, layout is generally as described.
