### ISSUE TITLE
Install TLS cert on demo server.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#57]
I have obtained a cert for "demo.smokealarm.org" from DigiCert.  But I'm not sure how to install it on our demo server, because I wasn't sure how to do the TLS/SSL configuration in `/etc/apache2/sites-available/000-default.conf` such that it would work with the ProxyPass and ProxyPassReverse we're doing with port 3000 on localhost.  Or maybe I should be doing all this in the `default-ssl.conf` file instead?

@trystant , your thoughts/experience welcome here :-).  I've done cert installation in standard Apache configurations before, so if it's just a matter of putting those usual lines in a config file on our server, I can do that.  I just wasn't sure how it interacts with the ProxyPass dance, if at all.  (In theory, I guess it shouldn't, right?)

**Comment by cecilia-donnelly** [comment]
I put our certificates on the server and updated `default-ssl.conf` in the obvious ways.  I think @kfogel made more changes.

**Comment by kfogel** [comment]
Done now.
