### ISSUE TITLE
Use bigger vertical spacing, bigger fonts, bigger Submit button on front page.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#59]
Once issues #56 and #47 are done, we should have room to put more vertical spacing between lines (especially the first two lines at the top, which as the attached screenshot shows are really kind of squished together righ tonw), use bigger fonts both in the text and in the input fields, and have a larger Submit button.  So we should do those things, unless I'm being overly optimistic, in which case let me know!

![screenshot from 2015-07-13 23-44-34](https://cloud.githubusercontent.com/assets/401111/8666594/8071ab20-29b9-11e5-9d86-87e410723409.png)

**Comment by nttaylor** [comment]
Closing following fa488c8

**Comment by nttaylor** [comment]
Setting the line-height of the upper box is having some unintuitive consequences whereby increasing line-height from 100% to around 140% actually causes lines of text to be more crowded. Increasing beyond 140% starts to spread them out again. The current value in base.css is one that looked good on my and @kfogel's browsers. I'm risking closing this again after 95bf166
