### ISSUE TITLE
Have one Address field, and just parse it.

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/smoke-alarm-portal#6]
(Note Karl edited this issue after it was opened, to make it mainly be about having a single Address field, instead of about the implementation question of using an address parsing library.)

Instead of separate fields for Address1, Address2, City, State, and ZIP, we should have one field.  Note that we've raised with the client the question of whether ZIP should be a separate field (since it's so important to the application, and having it be its own field would make it easier to indicate that it is mandatory).  I don't think we have the answer to that question yet, but for now, let's just go ahead and make a single Address field as a multi-line text box, and have the label indicate the need for ZIP -- e.g., "Full address (including ZIP Code)".

Note that we can use an existing library to parse the addresses that are submitted.  DataMade has an open source address parser, as one of their "Parserator" tools: http://datamade.us/data-tools/parserator/, which links to https://parserator.datamade.us/usaddress.  They offer the code, but they also offer it as an API with a tiny cost per API call.  IMHO we should incorporate the code ourselves, eventually, but for testing purposes and to speed things up right now, it's fine to call out to their API just to get a feel for how to use it without having to spend time integrating the code.

**Comment by kfogel** [comment]
By the way, this UI change can be done now, *before* we hook up the address parsing API/library.  All we need to extract right now is the ZIP Code, and that's pretty easy to get out of an address string -- it's just a regular expression match on the end of the string.  Basically:

1. Strip off any whitespace from the end of the string.
2. Strip off any "USA" or "U.S.A." or "United States", etc, from the end of the string (some people may put that at the end of an address)
3. The last thing in the string should now be either 5-digit ZIP or 5+4 digit ZIP.  In the latter case it will be either 9 digits in a row, or have a hyphen or a space, or whatnot.  Below is some example Python code for parsing from this point.

```python
#!/usr/bin/env python

# Example of how to cheaply parse ZIP codes out of addresses.

import re

# Various kinds of addresses ending with zip codes.  We'll assume the
# address has already had whitespace chopped from the right side, and
# that any country name (e.g., "USA") was already removed from the
# right side too.
zip_5 = "random address text 60602"
zip_5_dash_4 = "random address text 60602-1639"
zip_5_space_4 = "random address text 60602 1639"
zip_5_spaces_4 = "random address text    60602     1639"
zip_5_plus_4 = "random address text 60602+1639"
zip_5_underscore_4 = "random address text 60602_1639"
zip_9 = "random address text 606021639"

# One regular expression to rule them all, one regu... never mind.
zip_matcher = re.compile(".* +([0-9][0-9][0-9][0-9][0-9])(([-_+]{0,1}| +)[0-9][0-9][0-9][0-9]){0,1}$")

for zip_code in zip_5, zip_5_dash_4, zip_5_space_4, zip_5_spaces_4, zip_5_plus_4, zip_5_underscore_4, zip_9,:
    m = zip_matcher.match(zip_code)
    if m is not None:
        print "Parsing '%s':" % zip_code
        print "  5-digit portion: '%s'" % m.group(1)
        if m.group(2) is not None:
            # Due to the way we had to construct the regular expression, the
            # second match group is not just the 4 digits, but also starts
            # with any separator chars between the 5-digit group and the
            # 4-digit group.  So, strip those out.
            last_4_digits_match = re.match("[-_+ ]*([0-9][0-9][0-9][0-9])", m.group(2))
            last_4_digits = last_4_digits_match.group(1)
            print "  4-digit portion: '%s'" % last_4_digits
        else:
            print "  (no 4-digit portion)"
    else:
        # We should never reach this case.
        print "FAILED TO RECOGNIZE '%s' AS A ZIP CODE" % zip_code
    print ""
```

**Comment by cecilia-donnelly** [comment]
For now, the client has decided that we should use a separate zipcode field.  We *do* want to be able to autofill city and state based on an entered zipcode.

So, we'd see something like:

    Name: ________
    Zipcode: _______
    
    |Submit|

If the request didn't include a zipcode, instead of just showing an error, we'd slide down to show this:

    Name: ________
    _You must enter either a zipcode or a city and state_
    Zipcode: _______
    City: ___________
    State: [-------------]
    
    |Submit|

**Comment by kfogel** [comment]
Thanks for the example mockups, that helps.  All makes sense to me, except I assume somewhere in there there is an address line too (street and unit number, I mean).

**Comment by kfogel** [comment]
Closing as issue #23 now tracks the parts of this we care about.
