### ISSUE TITLE
Sort submissions by county, then Red Cross region

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/smoke-alarm-portal#7]
Based on the zipcode submitted, find the county where the smoke alarm is needed.

Once we have the list of counties per Red Cross region, we will match submissions to Red Cross region and handle them appropriately.  Some regions will not be participating in this pilot.  If the matched region is participating, send an email to the designated email address for that region, giving the details of the request, and show the user a confirmation page telling them this has been done. Otherwise, show the user a page with a short message explaining that Red Cross is not handling online requests for smoke alarm installation in their region yet, but giving contact information for the relevant Red Cross office to talk to about smoke alarm installation for that location.

**Comment by cecilia-donnelly** [comment]
Responding to @kfogel's comment in #11.

@trystant estimates that by Thursday (today) midday he will be able to determine Red Cross region based on zipcode and show a thank you page to addresses within the region and a "sorry" page to all others. 

Note that we're not handling the edge case where a zipcode is found in more than one county, which I opened issue #13 for.

**Comment by kfogel** [comment]
Happy dance, in that case!  I realize no actual email will go out yet, but
showing the geo-identification to Jim somehow will be good (even in couchdb
UI is fine).

Best,
-K

**Comment by kfogel** [comment]
As of commit 2e78c7d, the code is able to identify the Red Cross region, within the multi-state North Central Division, based on zip code, and the console debugging output shows this.  I don't yet know how to incorporate a dynamic message naming the region into the "Thank you" page and the "Sorry" page, though.  I probably won't have time to learn how to do that tonight, so please dive right in -- if I do get it done, I'll make a note here.

**Comment by kfogel** [comment]
Ah, the above is what issue #16 is about, so closing this issue.  See issue #16 for further work.
