### ISSUE TITLE
Automated mods to `package.json` expected?

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#78]
After doing the procedures in `INSTALL.md`, I found that I had unexpected local mods to `package.json`:

    $ git diff
    diff --git a/package.json b/package.json
    index 475e89c..f5553cd 100644
    --- a/package.json
    +++ b/package.json
    @@ -13,15 +13,15 @@
         "express": "^4.12.4",
         "forever": "^0.14.1",
         "jade": "~1.9.2",
    +    "mailgun-js": "~0.7.1",
         "morgan": "~1.5.3",
         "nano": "^6.1.3",
         "nanoid": "git+https://github.com/tcha-tcho/nanoid.git",
         "pg": "^4.4.0",
         "sanity": "^0.2.1",
    -    "sequelize": "^3.3.2",
    +    "sequelize": "^3.4.1",
         "sequelize-cli": "^1.7.0",
    -    "serve-favicon": "~2.2.1",
    -    "mailgun-js": "~0.7.1"
    +    "serve-favicon": "~2.2.1"
       },
       "devDependencies": {
         "chai": "^3.0.0",
    $ 

Is this expected?  Should I commit them?

**Comment by trystant** [comment]
`npm install` makes modifications to package.json. They are to be expected.

On Sun, Jul 19, 2015 at 4:18 AM, Karl Fogel <notifications@github.com>
wrote:

> After doing the procedures in INSTALL.md, I found that I had unexpected
> local mods to package.json:
>
> $ git diff
> diff --git a/package.json b/package.json
> index 475e89c..f5553cd 100644
> --- a/package.json
> +++ b/package.json
> @@ -13,15 +13,15 @@
>      "express": "^4.12.4",
>      "forever": "^0.14.1",
>      "jade": "~1.9.2",
> +    "mailgun-js": "~0.7.1",
>      "morgan": "~1.5.3",
>      "nano": "^6.1.3",
>      "nanoid": "git+https://github.com/tcha-tcho/nanoid.git",
>      "pg": "^4.4.0",
>      "sanity": "^0.2.1",
> -    "sequelize": "^3.3.2",
> +    "sequelize": "^3.4.1",
>      "sequelize-cli": "^1.7.0",
> -    "serve-favicon": "~2.2.1",
> -    "mailgun-js": "~0.7.1"
> +    "serve-favicon": "~2.2.1"
>    },
>    "devDependencies": {
>      "chai": "^3.0.0",
> $
>
> Is this expected? Should I commit them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenTechStrategies/smoke-alarm-portal/issues/78>.
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant

**Comment by kfogel** [comment]
So they should always be committed, when they happen?

**Comment by trystant** [comment]
Yup. Commit package.json when updating

**Comment by trystant** [comment]
There's a larger conversation to be had.

In JS development, there are quite a few processes that have an impact on other files in the system. The Gruntfile lists tasks which change, remove or add files depending on function. Is it important that each of those changes be detailed and documented?

**Comment by kfogel** [comment]
I think it's not important that each such change be carefully documented, since the changes are generated automagically anyway -- we can presume the system knows what it's doing.  What we do need to document is the fact that these changes are expected and that humans should commit them.  Which points to the need for a `DEVELOPMENT.md` file :-), but that's getting out of scope for this issue.  I'll close this ticket.  I'm not going to file a new one for creating `DEVELOPMENT.md` -- that's the sort of thing that, if we need it, we'll know we need it & won't forget.
