### ISSUE TITLE
Match styles to DCSOps

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/smoke-alarm-portal#8]
The text boxes and submit button should match the styling in DCSOps, per @kfogel in https://github.com/OpenTechStrategies/smoke-alarm-portal/issues/4#issuecomment-112402646.

>The styings should be similar to those of DCSOps (see https://www.dcsops.org/, and sources should be under https://github.com/redcross. 

[...]

>The font in DCSOps is Helvetica New.

**Comment by cecilia-donnelly** [comment]
Hey, @nttaylor, we should now be able to log in to DCSOps and get the relevant style points.  I think the main changes will be in the text boxes, selects, and possibly the submit buttons.

Also, it sounds like we should be using Helvetica New.

**Comment by cecilia-donnelly** [comment]
@nttaylor, let's have this done by next Tuesday at noon (central) (see the new milestone).

**Comment by nttaylor** [comment]
I think this can be closed? Obviously the two websites look very different but what commonalities they have should have the same appearance. See commit 18478eb above for details.

**Comment by kfogel** [comment]
Yup -- closing.  Thanks, Noel!
